name: Cleanup Expired Registrations

on:
  schedule:
    # Ini adalah jadwal cron: "setiap 15 menit"
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cleanup Endpoint
        run: |
          curl --fail --location -X POST \
            -H 'Authorization: Bearer fpy3Wjpxf1h7319aaj2fG6rsqxkMwAni' \
            "https://prfxiii.com/api/cron/cleanup-registrations"