name: Cleanup Expired Registrations

on:
  # Jalankan workflow ini sesuai jadwal
  schedule:
    # Ini adalah jadwal cron: "setiap 15 menit"
    - cron: '0 * * * *'
  # Tambahkan ini agar Anda bisa menjalankannya secara manual dari tab Actions
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cleanup Endpoint
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "https://www.prfxiii.com/api/cron/cleanup-registrations"